version: "3.10"
networks:
  local:
    driver: bridge
    name: cloud-web-app-network

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - local

    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - local

    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - local
